### ISSUE TITLE
Couldn't run detectionScript.py

### ISSUE THREAD

**Issue by mlkvr** [aelmiger/chessboard2fen#1] opened 2020-12-29 02:29 UTC
Traceback (most recent call last):
  File "detectionScript.py", line 73, in <module>
    cd.main()
  File "detectionScript.py", line 47, in main
    board = Chessboard()
  File "/content/chessboard2fen/chessboard.py", line 29, in __init__
    self.engine = chess.engine.SimpleEngine.popen_uci("./engine/stockfish")
AttributeError: module 'chess.engine' has no attribute 'SimpleEngine'

**Comment by aelmiger** [comment] 2020-12-30 10:24
What os are you running this on?
It appears to be an issue with your stockfish binaries. 
Download the binaries of your os and replace the binary in the engine folder.
https://stockfishchess.org/download/

**Comment by mlkvr** [comment] 2020-12-31 04:14
I'm willing use it on google colab -which runs linux on VM- and i tried all the binaries but got the same error thanks for your time.

**Comment by aelmiger** [comment] 2021-01-08 17:14
I cannot reproduce your issue. I am assuming, that stockfish binaries won't run on google colab.
Will close this issue for now.

**Closed as completed** 2021-01-08 17:14 UTC
